#!/usr/bin/env python3
"""
Build necom `address.sql` from post-merger Vietnam sources:
  - resources/address/provinces.sql (34 provinces)
  - resources/address/wards.sql   (wards → province_code)

Output schema matches JPA:
  - province(id, created_at, updated_at, created_by, updated_by, name, code)
  - ward(id, created_at, updated_at, created_by, updated_by, name, code, province_id)

`province.code` = administrative province_code (e.g. '01').
`ward.code`     = ward_code from source (e.g. '00004').

Usage (from necom-server):
  python3 scripts/build_address_sql.py
  python3 scripts/build_address_sql.py --fix-data-sql

Maven (same as the two commands above, includes --fix-data-sql):
  mvn generate-resources -Pgen-address-sql
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "src" / "main" / "resources"
PROVINCES_SQL = RES / "address" / "provinces.sql"
WARDS_SQL = RES / "address" / "wards.sql"
OUT_ADDRESS = RES / "address.sql"
DATA_SQL = RES / "data.sql"

TS = "'2023-02-15 00:00:00'"


def parse_provinces(path: Path) -> list[tuple[int, str, str]]:
    """Return list of (id, province_code, name) from phpMyAdmin dump."""
    text = path.read_text(encoding="utf-8")
    rows: list[tuple[int, str, str]] = []
    # (id, 'province_code', 'name', ...
    for m in re.finditer(
        r"\((\d+),\s*'([^']+)',\s*'([^']*)',\s*'[^']*',\s*'[^']*',\s*'[^']*',\s*'[^']*'",
        text,
    ):
        rows.append((int(m.group(1)), m.group(2), m.group(3)))
    rows.sort(key=lambda r: r[0])
    return rows


def parse_wards(path: Path) -> list[tuple[int, str, str, str]]:
    """Return list of (id, ward_code, name, province_code)."""
    text = path.read_text(encoding="utf-8")
    rows: list[tuple[int, str, str, str]] = []
    pat = re.compile(
        r"INSERT INTO `wards`\s*\([^)]+\)\s*VALUES\s*\((\d+),\s*'([^']+)',\s*'((?:[^'\\]|\\.)*)',\s*'([^']+)'",
        re.IGNORECASE,
    )
    for line in text.splitlines():
        m = pat.search(line)
        if not m:
            continue
        wid, wcode, name, pcode = m.group(1), m.group(2), m.group(3), m.group(4)
        name = name.replace("\\'", "'").replace("\\\\", "\\")
        rows.append((int(wid), wcode, name, pcode))
    rows.sort(key=lambda r: r[0])
    return rows


def build_code_to_province_id(provinces: list[tuple[int, str, str]]) -> dict[str, int]:
    return {code: pid for pid, code, _ in provinces}


def write_address_sql(
    provinces: list[tuple[int, str, str]],
    wards: list[tuple[int, str, str, str]],
    out: Path,
) -> None:
    code_to_pid = build_code_to_province_id(provinces)
    lines: list[str] = [
        "-- Generated by scripts/build_address_sql.py from address/provinces.sql + address/wards.sql",
        "-- Vietnam admin units after merger: 34 provinces, wards under province (no district).",
        "",
        "-- Client charset for string literals (avoids mojibake when server default is latin1)",
        "SET NAMES utf8mb4;",
        "SET CHARACTER SET utf8mb4;",
        "",
        "DROP TABLE IF EXISTS ward;",
        "DROP TABLE IF EXISTS district;",
        "DROP TABLE IF EXISTS province;",
        "",
        "CREATE TABLE province",
        "(",
        "    id         BIGINT AUTO_INCREMENT NOT NULL,",
        "    created_at datetime              NOT NULL,",
        "    updated_at datetime              NOT NULL,",
        "    created_by BIGINT                NULL,",
        "    updated_by BIGINT                NULL,",
        "    name       VARCHAR(255)          NOT NULL,",
        "    code       VARCHAR(35)           NOT NULL,",
        "    CONSTRAINT pk_province PRIMARY KEY (id)",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        "",
        "CREATE TABLE ward",
        "(",
        "    id          BIGINT AUTO_INCREMENT NOT NULL,",
        "    created_at  datetime              NOT NULL,",
        "    updated_at  datetime              NOT NULL,",
        "    created_by  BIGINT                NULL,",
        "    updated_by  BIGINT                NULL,",
        "    name        VARCHAR(255)          NOT NULL,",
        "    code        VARCHAR(35)           NOT NULL,",
        "    province_id BIGINT                NOT NULL,",
        "    CONSTRAINT pk_ward PRIMARY KEY (id)",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        "",
        "ALTER TABLE ward",
        "    ADD CONSTRAINT FK_WARD_ON_PROVINCE FOREIGN KEY (province_id) REFERENCES province (id);",
        "",
    ]

    lines.append(f"-- province TABLE: {len(provinces)} records (post-merger)")
    for pid, pcode, name in provinces:
        esc = name.replace("'", "''")
        lines.append(
            f"insert into province (id, created_at, updated_at, name, code) values ({pid}, {TS}, {TS}, '{esc}', '{pcode}');"
        )
    lines.append("")

    lines.append(f"-- ward TABLE: {len(wards)} records")
    for wid, wcode, wname, pcode in wards:
        pid = code_to_pid.get(pcode)
        if pid is None:
            raise SystemExit(f"Unknown province_code {pcode!r} for ward id {wid}")
        esc = wname.replace("'", "''")
        lines.append(
            f"insert into ward (id, created_at, updated_at, name, code, province_id) values ({wid}, {TS}, {TS}, '{esc}', '{wcode}', {pid});"
        )

    max_ward = max(w[0] for w in wards) if wards else 1
    lines.append("")
    lines.append(f"ALTER TABLE ward AUTO_INCREMENT = {max_ward + 1};")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def first_ward_by_province(wards: list[tuple[int, str, str, str]], provinces) -> dict[int, int]:
    code_to_pid = build_code_to_province_id(provinces)
    best: dict[int, int] = {}
    for wid, _code, _name, pcode in wards:
        pid = code_to_pid[pcode]
        if pid not in best:
            best[pid] = wid
    return best


def _split_sql_values_tuple(inner: str) -> list[str]:
    """Split comma-separated SQL scalar list (handles single-quoted strings)."""
    parts: list[str] = []
    cur: list[str] = []
    in_str = False
    i = 0
    while i < len(inner):
        ch = inner[i]
        if ch == "'":
            if in_str and i + 1 < len(inner) and inner[i + 1] == "'":
                cur.append("''")
                i += 2
                continue
            in_str = not in_str
            cur.append(ch)
            i += 1
            continue
        if ch == "," and not in_str:
            parts.append("".join(cur).strip())
            cur = []
            i += 1
            continue
        cur.append(ch)
        i += 1
    if cur:
        parts.append("".join(cur).strip())
    return parts


def fix_data_sql(provinces, wards) -> None:
    first = first_ward_by_province(wards, provinces)
    n = len(provinces)
    text = DATA_SQL.read_text(encoding="utf-8")
    marker = "-- address TABLE:"
    if marker not in text:
        raise SystemExit("data.sql: missing address TABLE marker")
    pre, post = text.split(marker, 1)
    m = re.search(r"^-- [^\n]+ TABLE:", post, re.MULTILINE)
    if not m:
        raise SystemExit("data.sql: no following TABLE section after address")
    addr_block = post[: m.start()]
    tail = post[m.start() :]
    # Flatten multi-line INSERT ... / VALUES ... pairs into single lines
    folded: list[str] = []
    buf = ""
    for line in addr_block.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.upper().startswith("INSERT INTO ADDRESS"):
            if buf:
                folded.append(buf.strip())
            buf = s
        elif buf:
            buf += " " + s
        if buf.rstrip().endswith(");"):
            folded.append(buf.strip())
            buf = ""
    if buf.strip():
        folded.append(buf.strip())
    lines_out: list[str] = []
    idx = 0
    for raw_stmt in folded:
        s = raw_stmt.strip()
        if not s.upper().startswith("INSERT INTO ADDRESS"):
            continue
        raw = s.rstrip(";")
        vm = re.match(
            r"INSERT INTO address\s*\((?P<cols>[^)]+)\)\s*VALUES\s*\((?P<vals>.+)\)",
            raw,
            re.I,
        )
        if not vm:
            continue
        cols = [c.strip().lower() for c in vm.group("cols").split(",")]
        parts = _split_sql_values_tuple(vm.group("vals"))
        if len(parts) != len(cols):
            raise SystemExit(f"Column/value mismatch in: {line[:120]}...")
        col_val = dict(zip(cols, parts))
        created = col_val.get("created_at", TS)
        updated = col_val.get("updated_at", TS)
        line_txt = col_val.get("line", "NULL")
        pid = (idx % n) + 1
        wid = first[pid]
        lines_out.append(
            f"INSERT INTO address (created_at, updated_at, line, province_id, ward_id)\n"
            f"VALUES ({created}, {updated}, {line_txt}, {pid}, {wid});"
        )
        idx += 1
    if not lines_out:
        raise SystemExit("No address INSERT rows found to rewrite")
    new_addr = (
        f"-- address TABLE: {len(lines_out)} records\n"
        + "\n".join(lines_out)
        + "\n\n"
    )
    new_text = pre + new_addr + tail
    DATA_SQL.write_text(new_text, encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fix-data-sql", action="store_true", help="Rewrite address inserts in data.sql")
    args = ap.parse_args()

    provinces = parse_provinces(PROVINCES_SQL)
    wards = parse_wards(WARDS_SQL)
    if len(provinces) != 34:
        raise SystemExit(f"Expected 34 provinces, got {len(provinces)}")
    if not wards:
        raise SystemExit("No wards parsed")

    write_address_sql(provinces, wards, OUT_ADDRESS)
    print(f"Wrote {OUT_ADDRESS} ({len(provinces)} provinces, {len(wards)} wards)")

    if args.fix_data_sql:
        fix_data_sql(provinces, wards)
        print(f"Patched {DATA_SQL}")


if __name__ == "__main__":
    main()
